#[derive(Debug, Clone, PartialEq)]
pub enum Token {
    Keyword(TokenKeyword),
    Id(String),
    Colon,
    StringLiteral(String),
    IntegerLiteral(i32),
    _RealNumLiteral(f32),
    Period,
    LCurly,
    RCurly,
    LParen,
    RParen,
    Comment(String),
    Newline,
    Semicolon,
    Pound,
    Comma,
    LBracket,
    RBracket,
    Percent,
    Pipe,
    Assign,
    AssignOut,
    Plus,
    Minus,
    Asterisk,
    Divide,
    Equal,
    NotEqual,
    LessThan,
    GreaterThan,
    LessThanOrEqual,
    GreaterThanOrEqual,
    And,
    _Or,
    _XOr,
    _Mod,
    Not,
    Tilde,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TokenKeyword {
    Global,
    Tag,
    FunctionBlock,
    Function,
    And,
    Or,
    XOr,
    Mod,
    True,
    False,
    Not,
    Use,
    Return,
}

pub fn keyword_token_from_str(s: &str) -> Option<Token> {
    match s {
        "fb" => Some(Token::Keyword(TokenKeyword::FunctionBlock)),
        "fn" => Some(Token::Keyword(TokenKeyword::Function)),
        "global" => Some(Token::Keyword(TokenKeyword::Global)),
        "tag" => Some(Token::Keyword(TokenKeyword::Tag)),
        "and" => Some(Token::Keyword(TokenKeyword::And)),
        "or" => Some(Token::Keyword(TokenKeyword::Or)),
        "xor" => Some(Token::Keyword(TokenKeyword::XOr)),
        "mod" => Some(Token::Keyword(TokenKeyword::Mod)),
        "true" => Some(Token::Keyword(TokenKeyword::True)),
        "false" => Some(Token::Keyword(TokenKeyword::False)),
        "not" => Some(Token::Keyword(TokenKeyword::Not)),
        "use" => Some(Token::Keyword(TokenKeyword::Use)),
        "return" => Some(Token::Keyword(TokenKeyword::Return)),
        _ => None,
    }
}
